
def wrap():
    #put HTML tag around the text
    pass

def table_gen():
    #generate a blank HTML table
    pass

def letter_table():
    #insert the random letter, generated by the function below,
    #into the blank table, using format() function
    pass

def pic_table():
    #insert images into the blank table
    #including code to generate a list of html <img> tag
    pass

def random_let():
    #generate random letter for the random letter table
    #return a tuple of random letter
    pass




def main():
    #Since there are things in the HTML code that stays the same,
    #like the table and the heading, I'm thinking of using the format() function
    #to insert customizable things (in the config.txt file) into the html string


    #so my idea of the program is this: read the file for info.
    #Info about color will be put inside the <style> tag, put in a separate chunk
    #The table data, title and the author will be inside body, put them in another chunk
    #The images will be put in a string then passed as parameters to pic_table().
    #We will extract the dimension info and pass it to table_gen()
    #After having all the chunks ready we concatenate them and write to the file


    #this code is my test for reading the file
    with open('config.txt', 'r') as f:
        bodybg = f.readline()
        bodybg = bodybg[bodybg.find('\t'):].strip()
        #print(bodybg)

        cell1 = f.readline()
        cell1 = cell1[cell1.find('\t'):].strip()
        #print(cell1)

        cell2 = f.readline()
        cell2 = cell2[cell2.find('\t'):].strip()
        #print(cell2)

        
        bordercolor = f.readline()
        bordercolor = bordercolor[bordercolor.find('\t'):].strip()
        #print(bordercolor)

        borderpx = f.readline()
        borderpx = borderpx[borderpx.find('\t'):].strip()
        #print(borderpx)

        authors = f.readline()
        authors = authors[authors.find('\t'):].strip()
        #print(authors)

        title = f.readline()
        title = title[title.find('\t'):].strip()
        #print(title)

        mode = f.readline().lower().strip()
        #print(mode)

        rows, cols = 0, 0
        if mode == 'images':
            #print('True')
            imgsList = f.readlines()
            #get the table dimension
            rows = len(imgsList)
            cols = imgsList[0].count('\t') + 1
            
            #create a list of image link
            imgsStr = str(imgsList)
            imgs = imgsStr.replace("['", '').replace("']",'').replace('\\n', '\\t').replace("', '", '').split('\\t')
            
        elif mode == 'letters':
            #get the table dimension
            dimension = f.readline().split('x')
            rows, cols = int(dimension[0]), int(dimension[1])
            

main()

